CREATE TABLE evento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    dt_creacion TIMESTAMPTZ NOT NULL,
    dt_actualizacion TIMESTAMPTZ,
    usuario_creacion VARCHAR(100) NOT NULL,
    usuario_actualizacion VARCHAR(100),
    id_programa BIGINT NOT NULL,
    nombre VARCHAR(180) NOT NULL,
    descripcion VARCHAR(2000),
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP NOT NULL,
    lugar VARCHAR(250) NOT NULL,
    cupo INTEGER,
    CONSTRAINT fk_evento_programa FOREIGN KEY (id_programa) REFERENCES programa(id),
    CONSTRAINT ck_evento_fechas CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT ck_evento_cupo CHECK (cupo IS NULL OR cupo >= 0)
);
CREATE INDEX ix_evento_programa ON evento(id_programa);
CREATE INDEX ix_evento_fecha_inicio ON evento(fecha_inicio);

CREATE TABLE inscripcion_evento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    dt_creacion TIMESTAMPTZ NOT NULL,
    dt_actualizacion TIMESTAMPTZ,
    usuario_creacion VARCHAR(100) NOT NULL,
    usuario_actualizacion VARCHAR(100),
    id_evento BIGINT NOT NULL,
    id_beneficiario BIGINT NOT NULL,
    fecha_inscripcion TIMESTAMP NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'INSCRITO',
    CONSTRAINT fk_inscripcion_evento FOREIGN KEY (id_evento) REFERENCES evento(id),
    CONSTRAINT fk_inscripcion_beneficiario FOREIGN KEY (id_beneficiario) REFERENCES beneficiario(id),
    CONSTRAINT uq_inscripcion_evento UNIQUE (id_evento, id_beneficiario)
);
CREATE INDEX ix_inscripcion_evento_evento ON inscripcion_evento(id_evento);
CREATE INDEX ix_inscripcion_evento_beneficiario ON inscripcion_evento(id_beneficiario);
