CREATE TABLE usuario (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 version BIGINT NOT NULL DEFAULT 0, activo BOOLEAN NOT NULL DEFAULT TRUE,
 dt_creacion TIMESTAMPTZ NOT NULL, dt_actualizacion TIMESTAMPTZ,
 usuario_creacion VARCHAR(100) NOT NULL, usuario_actualizacion VARCHAR(100),
 nombre_usuario VARCHAR(100) NOT NULL UNIQUE,
 nombre_completo VARCHAR(200) NOT NULL,
 clave VARCHAR(100) NOT NULL,
 rol VARCHAR(20) NOT NULL CHECK (rol IN ('ADMIN','OPERADOR','CONSULTA'))
);
CREATE FUNCTION proteger_auditoria() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 RAISE EXCEPTION 'El historial de auditoria no permite modificaciones ni borrados';
END;
$$;
CREATE TRIGGER auditoria_inmutable BEFORE UPDATE OR DELETE ON auditoria
FOR EACH ROW EXECUTE FUNCTION proteger_auditoria();
