CREATE TABLE auditoria (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 entidad VARCHAR(80) NOT NULL, id_registro BIGINT NOT NULL,
 operacion VARCHAR(80) NOT NULL, usuario VARCHAR(100) NOT NULL,
 fecha TIMESTAMPTZ NOT NULL, detalle TEXT NOT NULL
);

CREATE TABLE beneficiario (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 version BIGINT NOT NULL DEFAULT 0, activo BOOLEAN NOT NULL DEFAULT TRUE,
 dt_creacion TIMESTAMPTZ NOT NULL, dt_actualizacion TIMESTAMPTZ,
 usuario_creacion VARCHAR(100) NOT NULL, usuario_actualizacion VARCHAR(100),
primer_nombre VARCHAR(100) NOT NULL,
segundo_nombre VARCHAR(100),
primer_apellido VARCHAR(100) NOT NULL,
segundo_apellido VARCHAR(100),
tipo_documento VARCHAR(20),
numero_documento VARCHAR(40),
fecha_nacimiento DATE,
celular VARCHAR(30),
municipio VARCHAR(150),
direccion VARCHAR(250), codigo_interno VARCHAR(40) NOT NULL UNIQUE, nombre_normalizado VARCHAR(450) NOT NULL, CONSTRAINT uq_beneficiario_documento UNIQUE(tipo_documento, numero_documento), CONSTRAINT ck_documento_completo CHECK ((tipo_documento IS NULL) = (numero_documento IS NULL))
);

CREATE TABLE programa (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 version BIGINT NOT NULL DEFAULT 0, activo BOOLEAN NOT NULL DEFAULT TRUE,
 dt_creacion TIMESTAMPTZ NOT NULL, dt_actualizacion TIMESTAMPTZ,
 usuario_creacion VARCHAR(100) NOT NULL, usuario_actualizacion VARCHAR(100),
nombre VARCHAR(150) NOT NULL,
descripcion VARCHAR(2000), CONSTRAINT uq_programa UNIQUE(nombre)
);

CREATE TABLE participacion (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 version BIGINT NOT NULL DEFAULT 0, activo BOOLEAN NOT NULL DEFAULT TRUE,
 dt_creacion TIMESTAMPTZ NOT NULL, dt_actualizacion TIMESTAMPTZ,
 usuario_creacion VARCHAR(100) NOT NULL, usuario_actualizacion VARCHAR(100),
id_beneficiario BIGINT NOT NULL,
id_programa BIGINT NOT NULL,
periodo VARCHAR(40) NOT NULL,
fecha_ingreso DATE NOT NULL,
observaciones VARCHAR(2000), CONSTRAINT uq_participacion UNIQUE(id_beneficiario, id_programa, periodo)
);

CREATE TABLE atencion (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 version BIGINT NOT NULL DEFAULT 0, activo BOOLEAN NOT NULL DEFAULT TRUE,
 dt_creacion TIMESTAMPTZ NOT NULL, dt_actualizacion TIMESTAMPTZ,
 usuario_creacion VARCHAR(100) NOT NULL, usuario_actualizacion VARCHAR(100),
id_participacion BIGINT NOT NULL,
fecha_atencion DATE NOT NULL,
tipo_atencion VARCHAR(150) NOT NULL,
observaciones VARCHAR(2000), clave_idempotencia VARCHAR(100) NOT NULL UNIQUE, hash_solicitud VARCHAR(64) NOT NULL
);

CREATE TABLE seguimiento (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 version BIGINT NOT NULL DEFAULT 0, activo BOOLEAN NOT NULL DEFAULT TRUE,
 dt_creacion TIMESTAMPTZ NOT NULL, dt_actualizacion TIMESTAMPTZ,
 usuario_creacion VARCHAR(100) NOT NULL, usuario_actualizacion VARCHAR(100),
id_participacion BIGINT NOT NULL,
fecha_seguimiento DATE NOT NULL,
fecha_proximo_seguimiento DATE,
estado_seguimiento VARCHAR(255) NOT NULL,
observaciones VARCHAR(2000) NOT NULL, clave_idempotencia VARCHAR(100) NOT NULL UNIQUE, hash_solicitud VARCHAR(64) NOT NULL
);

CREATE TABLE familia (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 version BIGINT NOT NULL DEFAULT 0, activo BOOLEAN NOT NULL DEFAULT TRUE,
 dt_creacion TIMESTAMPTZ NOT NULL, dt_actualizacion TIMESTAMPTZ,
 usuario_creacion VARCHAR(100) NOT NULL, usuario_actualizacion VARCHAR(100),
nombre VARCHAR(150) NOT NULL,
direccion VARCHAR(250),
municipio VARCHAR(150)
);

CREATE TABLE integrante_familia (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 version BIGINT NOT NULL DEFAULT 0, activo BOOLEAN NOT NULL DEFAULT TRUE,
 dt_creacion TIMESTAMPTZ NOT NULL, dt_actualizacion TIMESTAMPTZ,
 usuario_creacion VARCHAR(100) NOT NULL, usuario_actualizacion VARCHAR(100),
id_familia BIGINT NOT NULL,
id_beneficiario BIGINT NOT NULL,
parentesco VARCHAR(100) NOT NULL, CONSTRAINT uq_integrante UNIQUE(id_familia, id_beneficiario)
);

CREATE TABLE catalogo (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 version BIGINT NOT NULL DEFAULT 0, activo BOOLEAN NOT NULL DEFAULT TRUE,
 dt_creacion TIMESTAMPTZ NOT NULL, dt_actualizacion TIMESTAMPTZ,
 usuario_creacion VARCHAR(100) NOT NULL, usuario_actualizacion VARCHAR(100),
tipo VARCHAR(50) NOT NULL,
codigo VARCHAR(50) NOT NULL,
nombre VARCHAR(150) NOT NULL, CONSTRAINT uq_catalogo UNIQUE(tipo, codigo)
);

ALTER TABLE participacion ADD FOREIGN KEY (id_beneficiario) REFERENCES beneficiario(id);
CREATE INDEX ix_participacion_id_beneficiario ON participacion(id_beneficiario);

ALTER TABLE participacion ADD FOREIGN KEY (id_programa) REFERENCES programa(id);
CREATE INDEX ix_participacion_id_programa ON participacion(id_programa);

ALTER TABLE atencion ADD FOREIGN KEY (id_participacion) REFERENCES participacion(id);
CREATE INDEX ix_atencion_id_participacion ON atencion(id_participacion);

ALTER TABLE seguimiento ADD FOREIGN KEY (id_participacion) REFERENCES participacion(id);
CREATE INDEX ix_seguimiento_id_participacion ON seguimiento(id_participacion);

ALTER TABLE integrante_familia ADD FOREIGN KEY (id_familia) REFERENCES familia(id);
CREATE INDEX ix_integrante_familia_id_familia ON integrante_familia(id_familia);

ALTER TABLE integrante_familia ADD FOREIGN KEY (id_beneficiario) REFERENCES beneficiario(id);
CREATE INDEX ix_integrante_familia_id_beneficiario ON integrante_familia(id_beneficiario);

CREATE INDEX ix_beneficiario_nombre ON beneficiario(nombre_normalizado);
