CREATE TABLE importacion (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 huella VARCHAR(64) NOT NULL UNIQUE,
 nombre_archivo VARCHAR(255) NOT NULL,
 fecha TIMESTAMPTZ NOT NULL,
 usuario VARCHAR(100) NOT NULL,
 configuracion TEXT NOT NULL
);
CREATE TABLE fila_importacion (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_importacion BIGINT NOT NULL REFERENCES importacion(id),
 numero_fila INTEGER NOT NULL,
 originales TEXT NOT NULL,
 normalizados TEXT NOT NULL,
 estado VARCHAR(30) NOT NULL CHECK (estado IN ('NUEVO','IMPORTADO','DUPLICADO','PENDIENTE','ERROR','OMITIDO','VINCULADO')),
 motivo VARCHAR(2000) NOT NULL,
 id_beneficiario BIGINT REFERENCES beneficiario(id),
 candidatos VARCHAR(2000),
 UNIQUE(id_importacion, numero_fila)
);
CREATE INDEX ix_fila_importacion ON fila_importacion(id_importacion, estado);
CREATE TABLE control_importacion (id BIGINT PRIMARY KEY);
INSERT INTO control_importacion(id) VALUES (1);
